In [ ]:
## Upload files

from google.colab import files
uploaded = files.upload()

In [ ]:
## Create pandas dataframe

import numpy as np
import pandas as pd

df = pd.read_excel('traffic.xlsx')
df1 = pd.read_excel('Day1_new.xlsx')
df2 = pd.read_excel('Day2_new.xlsx')
df3 = pd.read_excel('Day3_new.xlsx')
df4 = pd.read_excel('Day4_new.xlsx')
df5 = pd.read_excel('Day5_new.xlsx')
df6 = pd.read_excel('Day6_new.xlsx')
df7 = pd.read_excel('Day7_new.xlsx')
df8 = pd.read_excel('Day8_new.xlsx')
df_test1 = pd.read_excel('Test1_new.xlsx')
df_test1_or = pd.read_excel('Test1_original.xlsx')

In [ ]:
df8

In [ ]:
df[:30]

In [ ]:
## Imputed null value in missing values

df = df.fillna(0)
df1 = df1.fillna(0)
df2 = df2.fillna(0)
df3 = df3.fillna(0)
df4 = df4.fillna(0)
df5 = df5.fillna(0)
df6 = df6.fillna(0)
df7 = df7.fillna(0)
df8 = df8.fillna(0)
df_test1 = df_test1.fillna(0)
df_test1_or = df_test1_or.fillna(0)
df8[:10]

2  2.1  Unnamed: 2  Unnamed: 3    1
0  2.0  0.0         2.0         1.0  3.0
1  3.0  0.0         4.0         1.0  4.0
2  2.0  2.0         2.0         1.0  0.0
3  4.0  1.0         1.0         0.0  1.0
4  3.0  0.0         5.0         0.0  0.0
5  3.0  1.0         3.0         0.0  1.0
6  1.0  2.0         1.0         0.0  2.0
7  1.0  0.0         6.0         1.0  6.0
8  0.0  2.0         3.0         0.0  1.0
9  2.0  2.0         3.0         0.0  1.0

In [ ]:
## Create an numpy array

arr = np.array(df)
arr1 = np.array(df1)
arr2 = np.array(df2)
arr3 = np.array(df3)
arr4 = np.array(df4)
arr5 = np.array(df5)
arr6 = np.array(df6)
arr7 = np.array(df7)
arr8 = np.array(df8)
arr_test1 = np.array(df_test1)
arr_test1_or = np.array(df_test1_or)

In [ ]:
## Add flatten

flat = arr.flatten('C')
flat1 = arr1.flatten('C')
flat2 = arr2.flatten('C')
flat3 = arr3.flatten('C')
flat4 = arr4.flatten('C')
flat5 = arr5.flatten('C')
flat6 = arr6.flatten('C')
flat7 = arr7.flatten('C')
flat8 = arr8.flatten('C')
arr_test1 = arr_test1.flatten('C')
arr_test1_or = arr_test1_or.flatten('C')

arr_test1_or

array([2., 2., 0., ..., 2., 1., 3.])

In [ ]:
flat1

array([1., 0., 2., ..., 2., 1., 3.])

In [ ]:
flat2.shape

(1095,)

In [ ]:
## Create output array

output = flat
output1 = flat1
output2 = flat2
output3 = flat3
output4 = flat4
output5 = flat5
output6 = flat6
output7 = flat7
output8 = flat8
output_test1 = arr_test1
output_test1_or = arr_test1_or

output

array([2., 0., 1., ..., 5., 1., 1.])

In [1]:
## Randomly noise add
# 30% of the data will be given random noise
# 328 data is noisy

import random
sz = output.shape[0]
print(sz)

x = int(sz*0.3)
print(x)

noisy_indexes = random.sample(range(sz), x)
print(noisy_indexes)

NameError: name 'output' is not defined

In [ ]:
for item in noisy_indexes:
  output[item] = -1

for item in noisy_indexes:
  output1[item] = -1

for item in noisy_indexes:
  output2[item] = -1

for item in noisy_indexes:
  output3[item] = -1

for item in noisy_indexes:
  output4[item] = -1

for item in noisy_indexes:
  output5[item] = -1

for item in noisy_indexes:
  output6[item] = -1

for item in noisy_indexes:
  output7[item] = -1

for item in noisy_indexes:
  output8[item] = -1

print(output8)

[ 2.  0.  2. ...  5.  2. -1.]


In [ ]:
output8[1:30]

array([ 0.,  2.,  1.,  3.,  3., -1.,  4., -1.,  4.,  2.,  2.,  2.,  1.,
        0.,  4.,  1., -1.,  0.,  1.,  3.,  0.,  5.,  0.,  0., -1.,  1.,
        3., -1.,  1.])

In [ ]:
flat8[1:30]

array([ 0.,  2.,  1.,  3.,  3., -1.,  4., -1.,  4.,  2.,  2.,  2.,  1.,
        0.,  4.,  1., -1.,  0.,  1.,  3.,  0.,  5.,  0.,  0., -1.,  1.,
        3., -1.,  1.])

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
inp = np.array(df).flatten('C')
wrappedinput = np.array([output])
wrappedoutput = np.array([inp])


inp1 = np.array(df1).flatten('C')
wrappedinput1 = np.array([output1])
wrappedoutput1 = np.array([inp1])


inp2 = np.array(df2).flatten('C')
wrappedinput2 = np.array([output2])
wrappedoutput2 = np.array([inp2])


inp3 = np.array(df3).flatten('C')
wrappedinput3 = np.array([output3])
wrappedoutput3 = np.array([inp3])


inp4 = np.array(df4).flatten('C')
wrappedinput4 = np.array([output4])
wrappedoutput4 = np.array([inp4])


inp5 = np.array(df5).flatten('C')
wrappedinput5 = np.array([output5])
wrappedoutput5 = np.array([inp5])


inp6 = np.array(df6).flatten('C')
wrappedinput6 = np.array([output6])
wrappedoutput6 = np.array([inp6])


inp7 = np.array(df7).flatten('C')
wrappedinput7 = np.array([output7])
wrappedoutput7 = np.array([inp7])


inp8 = np.array(df8).flatten('C')
wrappedinput8 = np.array([output8])
wrappedoutput8 = np.array([inp8])

print(wrappedinput)

[[ 2.  0.  1. ...  5.  1. -1.]]


In [ ]:
#Create model

model = Sequential()
model.add(Dense(2000, input_dim=wrappedinput.shape[1], activation='relu'))
model.add(Dense(1000, activation='relu'))
model.add(Dense(500, activation='relu'))
model.add(Dense(1095))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(wrappedinput,wrappedoutput,verbose=0,batch_size=len(wrappedinput),epochs=10000)

pred = model.predict(wrappedinput)

print("Actual")
print(wrappedoutput)

print("Pred")
print(pred)

In [ ]:
#model1

model1 = Sequential()
model1.add(Dense(2000, input_dim=wrappedinput1.shape[1], activation='relu'))
model1.add(Dense(1000, activation='relu'))
model1.add(Dense(500, activation='relu'))
model1.add(Dense(1095))
model1.compile(loss='mean_squared_error', optimizer='adam')
model1.fit(wrappedinput1,wrappedoutput1,verbose=0,batch_size=len(wrappedinput1),epochs=10000)



In [ ]:
#model2

model2 = Sequential()
model2.add(Dense(2000, input_dim=wrappedinput2.shape[1], activation='relu'))
model2.add(Dense(1000, activation='relu'))
model2.add(Dense(500, activation='relu'))
model2.add(Dense(1095))
model2.compile(loss='mean_squared_error', optimizer='adam')
model2.fit(wrappedinput2,wrappedoutput2,verbose=0,batch_size=len(wrappedinput2),epochs=10000)

In [ ]:
#model3

model3 = Sequential()
model3.add(Dense(2000, input_dim=wrappedinput3.shape[1], activation='relu'))
model3.add(Dense(1000, activation='relu'))
model3.add(Dense(500, activation='relu'))
model3.add(Dense(1095))
model3.compile(loss='mean_squared_error', optimizer='adam')
model3.fit(wrappedinput3,wrappedoutput3,verbose=0,batch_size=len(wrappedinput3),epochs=10000)

In [ ]:
#model4

model4 = Sequential()
model4.add(Dense(2000, input_dim=wrappedinput4.shape[1], activation='relu'))
model4.add(Dense(1000, activation='relu'))
model4.add(Dense(500, activation='relu'))
model4.add(Dense(1095))
model4.compile(loss='mean_squared_error', optimizer='adam')
model4.fit(wrappedinput4,wrappedoutput4,verbose=0,batch_size=len(wrappedinput4),epochs=10000)

In [ ]:
#model6

model6 = Sequential()
model6.add(Dense(2000, input_dim=wrappedinput6.shape[1], activation='relu'))
model6.add(Dense(1000, activation='relu'))
model6.add(Dense(500, activation='relu'))
model6.add(Dense(1095))
model6.compile(loss='mean_squared_error', optimizer='adam')
model6.fit(wrappedinput6,wrappedoutput6,verbose=0,batch_size=len(wrappedinput6),epochs=10000)

In [ ]:
#model7

model7 = Sequential()
model7.add(Dense(2000, input_dim=wrappedinput7.shape[1], activation='relu'))
model7.add(Dense(1000, activation='relu'))
model7.add(Dense(500, activation='relu'))
model7.add(Dense(1095))
model7.compile(loss='mean_squared_error', optimizer='adam')
model7.fit(wrappedinput7,wrappedoutput7,verbose=0,batch_size=len(wrappedinput7),epochs=10000)

In [ ]:
# Connect to google drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
## Load model
import pickle
model = pickle.load(open('/content/drive/MyDrive/Thesis Output/model.pkl', 'rb'))
model1 = pickle.load(open('/content/drive/MyDrive/Thesis Output/model1.pkl', 'rb'))
model2 = pickle.load(open('/content/drive/MyDrive/Thesis Output/model2.pkl', 'rb'))
model3 = pickle.load(open('/content/drive/MyDrive/Thesis Output/model3.pkl', 'rb'))
model4 = pickle.load(open('/content/drive/MyDrive/Thesis Output/model4.pkl', 'rb'))
model6 = pickle.load(open('/content/drive/MyDrive/Thesis Output/model6.pkl', 'rb'))
model7 = pickle.load(open('/content/drive/MyDrive/Thesis Output/model7.pkl', 'rb'))


In [ ]:
import pickle
pickle.dump(model, open('model.pkl', 'wb'))
!cp model.pkl /content/drive/MyDrive/Thesis-Output

In [ ]:
pickle.dump(model1, open('model1.pkl', 'wb'))
!cp model1.pkl /content/drive/MyDrive/Thesis-Output

In [ ]:
pickle.dump(model2, open('model2.pkl', 'wb'))
!cp model2.pkl /content/drive/MyDrive/Thesis-Output

In [ ]:
pickle.dump(model3, open('model3.pkl', 'wb'))
!cp model3.pkl /content/drive/MyDrive/Thesis-Output

In [ ]:
pickle.dump(model4, open('model4.pkl', 'wb'))
!cp model4.pkl /content/drive/MyDrive/Thesis-Output

In [ ]:
pickle.dump(model6, open('model6.pkl', 'wb'))
!cp model6.pkl /content/drive/MyDrive/Thesis-Output

In [ ]:
pickle.dump(model7, open('model7.pkl', 'wb'))
!cp model7.pkl /content/drive/MyDrive/Thesis-Output

In [ ]:
import pickle
pickled_model0 = pickle.load(open('model.pkl', 'rb'))

In [ ]:
pred1 = pred1.reshape((219, 5))

array([[-9.9999964e-01, -9.9999934e-01,  9.9999946e-01, -1.0000007e+00,
         1.9999995e+00],
       [ 3.0000002e+00, -1.5459955e-07, -9.9999917e-01,  1.0000006e+00,
        -9.3132257e-09],
       [ 4.9999995e+00, -1.2107193e-07, -9.9999964e-01,  9.9999970e-01,
        -5.7648867e-07],
       [ 2.0000007e+00,  9.9999994e-01,  1.9999999e+00, -1.0000005e+00,
        -5.5879354e-07],
       [ 2.0000005e+00,  9.9999952e-01, -9.9999958e-01,  1.3113022e-06,
         9.9999964e-01],
       [ 5.0000010e+00, -6.7334622e-07, -2.0116568e-07, -6.0116872e-07,
         1.7136335e-07],
       [ 5.9999981e+00, -1.0000011e+00, -9.9999911e-01, -1.0000002e+00,
         1.0000001e+00],
       [ 4.9999990e+00, -6.1537139e-07,  9.9999923e-01,  7.7649020e-07,
        -1.2386590e-07],
       [-1.0000005e+00,  5.8952719e-07,  4.0000005e+00,  9.9999934e-01,
         1.9999995e+00],
       [ 2.9999995e+00, -9.9999982e-01, -1.0000002e+00, -4.6193600e-07,
        -1.0000000e+00]], dtype=float32)

In [ ]:
#Using model7 to predict test set wrappedinput8

pred8 = model7.predict(wrappedinput8)

1/1 [==============================] - 0s 172ms/step


In [ ]:
## Measure Accuracy

from sklearn import metrics
score = np.sqrt(metrics.mean_squared_error(pred8, wrappedoutput8))
print("Score (RMSE): {}".format(score))

score1 = np.sqrt(metrics.mean_absolute_error(pred8, wrappedoutput8))
print("Score (MAE): {}".format(score1))

Score (RMSE): 2.1015376094167473
Score (MAE): 1.161046982609224


In [ ]:
## Check predict vs true value

for i in range(50):
  print(round(pred8[0,i]), end= ' ')

print()
for i in range(50):
  print(round(wrappedoutput8[0,i]), end= ' ')

1 0 1 0 1 2 0 2 0 2 0 1 2 1 0 1 1 1 0 1 2 0 0 0 0 2 1 1 0 0 3 1 0 0 2 2 1 3 0 3 1 0 2 0 1 0 1 2 0 0 
2 0 2 1 3 3 0 4 1 4 2 2 2 1 0 4 1 1 0 1 3 0 5 0 0 3 1 3 0 1 1 2 1 0 2 1 0 6 1 6 0 2 3 0 1 2 2 3 0 1 

In [ ]:
pred8 = pred8.reshape((219, 5))

for i in range(219):
  for j in range(5):
    pred8[i,j] = (round(pred8[i,j]))

pred8

array([[1., 0., 1., 0., 1.],
       [2., 0., 2., 0., 2.],
       [0., 1., 2., 1., 0.],
       ...,
       [2., 1., 1., 0., 1.],
       [0., 1., 1., 0., 1.],
       [2., 0., 2., 1., 0.]], dtype=float32)

In [ ]:
excelout = pd.DataFrame(pred8, columns=['Rickshaw/Bicycle', 'Private Car', 'CNG', 'Bus/Truck','Motorcycle'])
excelout

Rickshaw/Bicycle  Private Car  CNG  Bus/Truck  Motorcycle
0                 1.0          0.0  1.0        0.0         1.0
1                 2.0          0.0  2.0        0.0         2.0
2                 0.0          1.0  2.0        1.0         0.0
3                 1.0          1.0  1.0        0.0         1.0
4                 2.0          0.0  0.0        0.0         0.0
..                ...          ...  ...        ...         ...
214               0.0          0.0  3.0        1.0         0.0
215               1.0          0.0  0.0        0.0         0.0
216               2.0          1.0  1.0        0.0         1.0
217               0.0          1.0  1.0        0.0         1.0
218               2.0          0.0  2.0        1.0         0.0

[219 rows x 5 columns]

In [ ]:
excelout.to_excel("predicted8.xlsx")

In [ ]:
output_test1 = np.array([output_test1])
# wrappedoutput8.shape
output_test1.shape

(1, 1095)

In [ ]:
output_test1_or = np.array([output_test1_or])
output_test1_or.shape

(1, 1095)

In [ ]:
#Using model to predict test set Test1_new

pred9 = model7.predict(output_test1)

1/1 [==============================] - 0s 39ms/step


In [ ]:
from sklearn import metrics
score = np.sqrt(metrics.mean_squared_error(pred9, output_test1_or))
print("Score (RMSE): {}".format(score))

score1 = np.sqrt(metrics.mean_absolute_error(pred9, output_test1_or))
print("Score (MAE): {}".format(score1))

Score (RMSE): 2.343664449963408
Score (MAE): 1.266831539952977


In [ ]:
## Check predict vs true value

for i in range(50):
  print(round(pred9[0,i]), end= ' ')

print()
for i in range(50):
  print(round(output_test1_or[0,i]), end= ' ')

1 0 1 0 1 1 0 2 0 2 1 0 2 1 0 1 1 1 0 2 1 0 0 0 0 2 1 1 0 0 3 1 0 0 2 2 0 3 0 2 2 0 1 0 1 0 1 2 0 0 
2 2 0 0 1 2 0 2 1 3 3 0 4 1 4 4 2 3 1 0 4 1 1 0 1 3 0 5 0 0 2 1 3 0 1 1 2 1 0 2 1 0 6 1 6 0 2 3 0 1 

In [ ]:
pred9 = pred9.reshape((219, 5))

for i in range(219):
  for j in range(5):
    pred9[i,j] = (round(pred9[i,j]))

pred9

array([[1., 0., 1., 0., 1.],
       [1., 0., 2., 0., 2.],
       [1., 0., 2., 1., 0.],
       ...,
       [2., 0., 1., 0., 1.],
       [0., 1., 1., 1., 1.],
       [2., 0., 2., 1., 0.]], dtype=float32)

In [ ]:
excelout1 = pd.DataFrame(pred9, columns=['Rickshaw/Bicycle', 'Private Car', 'CNG', 'Bus/Truck','Motorcycle'])
excelout1

Rickshaw/Bicycle  Private Car  CNG  Bus/Truck  Motorcycle
0                 1.0          0.0  1.0        0.0         1.0
1                 1.0          0.0  2.0        0.0         2.0
2                 1.0          0.0  2.0        1.0         0.0
3                 1.0          1.0  1.0        0.0         2.0
4                 1.0          0.0  0.0        0.0         0.0
..                ...          ...  ...        ...         ...
214               0.0          0.0  2.0        0.0         0.0
215               1.0          0.0  0.0        1.0         0.0
216               2.0          0.0  1.0        0.0         1.0
217               0.0          1.0  1.0        1.0         1.0
218               2.0          0.0  2.0        1.0         0.0

[219 rows x 5 columns]

In [ ]:
excelout1.to_excel("predicted9.xlsx")